
services:
  - type: web
    name: alpha-blade-dashboard
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
